version: "3.9"

services:

  backend:
    build: ./purchase-backend
    container_name: fastapi-backend
    ports:
      - "8000:8000"
    restart: always


  frontend:
    build: ./purchase-portal
    container_name: react-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: always

    # ...existing code...

    # ...existing code...
    environment:
      ORACLE_HOST: "172.16.0.9"
      ORACLE_PORT: "1521"
      ORACLE_SERVICE: "orcldr"
      ORACLE_USER: "erpdev"
      ORACLE_PASSWORD: "erpdevtest"
# ...existing code...